name: pomdp-planning
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.6
  - ca-certificates
  - openssl
  - pip
  - pip:
      - -r requirements.txt
      - -r requirements_dev.txt