num_sims: 64 # number of simulations to run (positive int)
ucb_constant: 2. # exploration constant used by MCTS (positive float)
horizon: 100 # length of problem (positive int)
rollout_depth: 10 # length of rollouts to evaluate leafs (positive int)
max_tree_depth: 100 # max depth of tree (positive int)
discount_factor: 0.99 # discount factor of the discounted return [0,1]
num_particles: 128 # number of particles to track in belief
learning_rate: 0.1 # learning rate
backup_operator: mc  # backup operator used in MCTS: "mc" or "max"
# For any model: "max_q", "soft_q", "max_visits", "visits_prob,
# If `model_output` == "value_and_prior": "max_prior" or "prior_prob"
# If `model_output` == "q_values": "max_q_model" or "soft_q_model"
action_selection: max_q
model_input: history # "state" or "history"
model_output: value_and_prior # "value_and_prior" or "q_values"
policy_target: soft_q # "soft_q" or "visits"
